### ISSUE TITLE
Your Counselor Channel for Applicants

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#64]
We talked today about having a channel for applicants that displays their counselor info. I think it can be called Your Counselor.

We're going to start by pulling this data from counselor page:

Photo
Name
Email
Phone

Then, we'll figure out how we want to connect pages to counselors in sales force.

**Comment by c-schwarze** [comment]
I added a basic counselor channel. Its on the homepage, third column.

**Comment by kelslundberg** [comment]
Awesome!

**Comment by c-schwarze** [comment]
We are planning on talking with Lisa about how to get the Salesforce URLs next meeting (monday the 12th).

**Comment by kelslundberg** [comment]
Also, we talked about using this style:

Name
Photo
Email/Phone
Gruber to write some text for the description below

![screen shot 2017-06-06 at 8 53 33 am](https://cloud.githubusercontent.com/assets/6525391/26832636/b348057c-4a95-11e7-87a7-fbc8ffbc1956.png)

**Comment by kelslundberg** [comment]
Remove like/love :) :)

**Comment by kelslundberg** [comment]
@d-freed is having a student create a spreadsheet for Lisa with all enrollment/admissions counselors for all schools along with the Cascade ID for their webpage.

I think all we need in the spreadsheet is Counselor Name and Cascade ID

**Comment by kelslundberg** [comment]
Spreadsheet is complete. I passed it to Lisa and Tim today.

**Comment by josiahtillman** [comment]
![screen shot 2017-06-15 at 10 34 35 am](https://user-images.githubusercontent.com/12627410/27193703-82c0a594-51c5-11e7-91f5-8cfbbe0b6e38.png)
This is where I'm at right now-- I like how the pop of color looks, but in context, the color is a bit strange when every other element is very neutral. The end color will depend on the aesthetic direction that portal goes with. 

I think this would look best without the channel bar on top, so it might be cool to add the option to drop that bar for certain channels.
![screen shot 2017-06-15 at 10 34 53 am](https://user-images.githubusercontent.com/12627410/27189208-4b7384e4-51b6-11e7-9789-f0319d3836ea.png)

Last thing-- in order for the images of the counselors to be pulled correctly into the circle crop, the images would need to be centered on the face. Each image has the face in a slightly different part of the image, so, if possible, could we add a cropped, square image to each counselor in cascade? That way, every counselor would show up correctly, rather than having the face off-center.

**Comment by josiahtillman** [comment]
Here's the new styling for the counselor channel. 

![screen shot 2017-06-21 at 4 10 34 pm](https://user-images.githubusercontent.com/12627410/27407045-8b2c1020-569c-11e7-801d-20abe27c6a16.png)


Now that we aren't using circle images, we won't need any cropped images. Let me know if you guys think there should be any other changes!

**Comment by kelslundberg** [comment]
Thanks so much! I think this is looking good!

I'm checking in with Lisa and Tim Hammer on what we need in sales force...

**Comment by c-schwarze** [comment]
Where are we at with this?

**Comment by c-schwarze** [comment]
We now have the counselor URLs in salesforce. 

@dstavem Could you get the salesforce URLs for a user and put that into a procedure that we can use? Let me know if you need more information.

**Comment by dstavem** [comment]
I have created a procedure here that returns admissions counselor URL:

bth_portal_channel_api.stu_admissions

If you end up needing additional admissions information in the future, it would likely go in this procedure also.

Also, correct me if I am wrong, but my understanding is that you will only be displaying this for students who are in the admissions process, and once they become students they will not see this anymore.  I have not done any filtering to exclude current students, but I am assuming that this will be happening on your end.  I wouldn't want current students to keep contacting an admissions counselor.  Let me know if you need me to do more with that.   Thanks!

Derek

**Comment by e-jameson** [comment]
This channel has been updated. I've spot-checked a few usernames that Derek gave me, so I think we can call testing good on this one.
